### ISSUE TITLE
Button not visible in sample storyboard

### ISSUE THREAD

**Issue by Oggerschummer** [arpitjain03/AJParticlesLoadingView#1]
Hi,
some minor issue: 
I ran the sample project on an iPad with iOS11.2 and the button was not visible.
You should e.g. add some bottom constraint + fixed height for the lower view plus 
giving the particle view a variable height.
Have some nice Holidays,
Thomas

**Comment by arpitjain03** [comment]
Hi @Oggerschummer,

Yes minor issue. I must have missed this. I have updated my code. You can clone the latest update.

Thanks
